DEFAULT_RULES = [
    {
        "id": "rule_port_scan",
        "name": "Port Scan Burst",
        "enabled": True,
        "severity": "HIGH",
        "description": "Detects rapid connections to many unique ports from a single source.",
        "config": {"window_sec": 30, "unique_ports": 12},
    },
    {
        "id": "rule_suspicious_port",
        "name": "High-Risk Port Contact",
        "enabled": True,
        "severity": "MEDIUM",
        "description": "Flags traffic to common high-risk service ports.",
        "config": {"ports": [23, 22, 445, 3389, 5900, 4444, 31337]},
    },
    {
        "id": "rule_dns_tunnel",
        "name": "Suspicious DNS Query",
        "enabled": True,
        "severity": "MEDIUM",
        "description": "Detects unusually long or deeply nested DNS queries.",
        "config": {"length_threshold": 35, "dot_threshold": 4},
    },
    {
        "id": "rule_outbound_spike",
        "name": "Outbound Spike",
        "enabled": True,
        "severity": "MEDIUM",
        "description": "Detects sudden spikes in outbound bytes per host.",
        "config": {"window_sec": 60, "multiplier": 4.0, "min_bytes": 200000},
    },
    {
        "id": "rule_proc_suspicious",
        "name": "Suspicious Process",
        "enabled": True,
        "severity": "HIGH",
        "description": "Flags suspicious process names or encoded PowerShell usage.",
        "config": {
            "keywords": ["mimikatz", "procdump", "nc.exe", "netcat", "rubeus", "psexec"],
            "powershell_flags": ["-enc", "-encodedcommand"],
        },
    },
    {
        "id": "rule_host_suspicious_conn",
        "name": "Host Suspicious Outbound",
        "enabled": True,
        "severity": "MEDIUM",
        "description": "Flags unusual outbound connections from host processes.",
        "config": {"ports": [4444, 1337, 9001, 5555]},
    },
    {
        "id": "rule_host_high_cpu",
        "name": "High CPU Utilization",
        "enabled": True,
        "severity": "LOW",
        "description": "Flags sustained high CPU usage on the host.",
        "config": {"threshold": 90},
    },
]
